### ISSUE TITLE
2.10: Compiler crashes when using `compileError`: SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError

### ISSUE THREAD

**Issue by lloydmeta** [lihaoyi/utest#68]
When using `compileError`, I'm seeing a compiler crash when running under 2.10 (ironic..).

Under 2.11, the same code fails properly (passes compilation)

The test code is [here](https://github.com/lloydmeta/enumeratum/blob/feature/scalajs/enumeratum-core/src/test/scala/enumeratum/EnumTests.scala#L136-L173) and in specific belongs to a PR I have opened to try [to support ScalaJS](https://github.com/lloydmeta/enumeratum/pull/9)

To reproduce, simply clone that project, switch to the `feature/scalajs` branch and do:

``` shell
$ sbt
> project coreJS
> +test
```

The error (under 2.10) is as follows:

``` console
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: 
     while compiling: /Users/l-chan/Documents/skala/enumeratum/enumeratum-core/.js/../src/test/scala/enumeratum/EnumTests.scala
        during phase: global=typer, atPhase=namer
     library version: version 2.10.4
    compiler version: version 2.10.4
  reconstructed args: -Xplugin:/Users/l-chan/.ivy2/cache/org.scala-js/scalajs-compiler_2.10.4/jars/scalajs-compiler_2.10.4-0.6.2.jar -Ywarn-nullary-unit -Xlog-free-terms -feature -Xlint -Ywarn-inaccessible -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/classes:/Users/l-chan/.sbt/boot/scala-2.10.4/lib/scala-library.jar -unchecked -classpath /Users/l-chan/Documents/skala/enumeratum/enumeratum-core/.js/target/scala-2.10/test-classes:/Users/l-chan/Documents/skala/enumeratum/enumeratum-core/.js/target/scala-2.10/classes:/Users/l-chan/Documents/skala/enumeratum/macros/.js/target/scala-2.10/classes:/Users/l-chan/.ivy2/cache/org.scala-js/scalajs-library_2.10/jars/scalajs-library_2.10-0.6.2.jar:/Users/l-chan/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/Users/l-chan/.ivy2/cache/org.scalamacros/quasiquotes_2.10/jars/quasiquotes_2.10-2.0.1.jar:/Users/l-chan/.ivy2/cache/com.lihaoyi/utest_sjs0.6_2.10/jars/utest_sjs0.6_2.10-0.3.1.jar:/Users/l-chan/.ivy2/cache/org.scala-js/scalajs-test-interface_2.10/jars/scalajs-test-interface_2.10-0.6.1.jar:/Users/l-chan/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.10/jars/scalac-scoverage-runtime_2.10-1.0.1.jar:/Users/l-chan/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.10/jars/scalac-scoverage-plugin_2.10-1.0.1.jar -deprecation -Ywarn-nullary-override -Ywarn-adapted-args

  last tree to typer: term NotSealed
              symbol: <none> (flags: )
   symbol definition: <none>
       symbol owners: 
      context owners: 

== Enclosing template or block ==

ModuleDef(
  0
  "NotSealed"
  Template(
    Enum[NotSealed] // parents
    ValDef(
      private
      "_"
      <tpt>
      <empty>
    )
    // 2 statements
    DefDef(
      0
      "<init>"
      []
      List(Nil)
      <tpt>
      Block(
        Apply(
          super."<init>"
          Nil
        )
        ()
      )
    )
    ValDef(
      0
      "values"
      <tpt>
      "findValues"
    )
  )
)

no-symbol does not have an owner
[error] no-symbol does not have an owner
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: no-symbol does not have an owner
[error] no-symbol does not have an owner
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: no-symbol does not have an owner
[error] no-symbol does not have an owner
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: no-symbol does not have an owner
[error] no-symbol does not have an owner
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: no-symbol does not have an owner
[error] no-symbol does not have an owner
SOMETHING WENT WRONG LOLS scala.reflect.internal.FatalError: no-symbol does not have an owner
[error] /Users/l-chan/Documents/skala/enumeratum/enumeratum-core/.js/../src/test/scala/enumeratum/EnumTests.scala:162: exception during macro expansion: 
[error] java.lang.AssertionError: assertion failed: class Class extends Enum[Foo] {
[error]   def <init>() = {
[error]     super.<init>();
[error]     ()
[error]   };
[error]   val values = findValues;
[error]   case object Bar extends Foo with scala.Product with scala.Serializable {
[error]     def <init>() = {
[error]       super.<init>();
[error]       ()
[error]     }
[error]   };
[error]   case object Baz extends Foo with scala.Product with scala.Serializable {
[error]     def <init>() = {
[error]       super.<init>();
[error]       ()
[error]     }
[error]   }
[error] }
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1756)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5583)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2433)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5570)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2$$anonfun$5.apply(Typers.scala:25)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2$$anonfun$5.apply(Typers.scala:25)
[error]     at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:727)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2.apply(Typers.scala:25)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2.apply(Typers.scala:25)
[error]     at scala.tools.nsc.typechecker.Contexts$Context.withMacrosEnabled(Contexts.scala:242)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$3.apply(Typers.scala:18)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$3.apply(Typers.scala:18)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$wrapper$1$1.apply(Typers.scala:19)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$wrapper$1$1.apply(Typers.scala:19)
[error]     at scala.tools.nsc.typechecker.Contexts$Context.withImplicitsEnabled(Contexts.scala:211)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$1.apply(Typers.scala:17)
[error]     at scala.reflect.macros.runtime.Typers$$anonfun$1.apply(Typers.scala:17)
[error]     at scala.reflect.macros.runtime.Typers$class.wrapper$1(Typers.scala:19)
[error]     at scala.reflect.macros.runtime.Typers$class.typeCheck(Typers.scala:25)
[error]     at scala.reflect.macros.runtime.Context.typeCheck(Context.scala:6)
[error]     at scala.reflect.macros.runtime.Context.typeCheck(Context.scala:6)
[error]     at utest.asserts.Asserts$.compileError(Asserts.scala:47)
[error]       * - compileError("""
[error]                       ^
[error] 7 errors found
[error] (coreJS/test:compileIncremental) Compilation failed
```

**Comment by alexeyr** [comment]
I just ran into the same problem.

**Comment by lihaoyi** [comment]
If it works correctly in 2.11, I'm going to punt on 2.10 and call this a wontfix. Feel free to re-open if it occurs in a more recent version
